/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;

/**
 *
 * @author tushaar
 */
public class Availability extends javax.swing.JFrame {

    /**
     * Creates new form Availability
     */
    private static Availability availabilityInstance = null ;
    
    public Availability() {
        initComponents();
    }

    static Availability getInstance() {
        if(availabilityInstance == null)
            availabilityInstance = new Availability() ;
        return availabilityInstance ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check Availability");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1026, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 34, 45));
        jLabel1.setText("Ticket Availability");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 214, 44);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 34, 45));
        jLabel2.setText("Select Route");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 130, 111, 21);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 34, 45));
        jLabel3.setText("Flight Number");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 21));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(459, 140, 240, 21);

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(745, 140, 245, 29);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 34, 45));
        jLabel4.setText("Date of Journey");
        jLabel4.setMaximumSize(new java.awt.Dimension(323, 21));
        jLabel4.setMinimumSize(new java.awt.Dimension(323, 21));
        jLabel4.setPreferredSize(new java.awt.Dimension(300, 21));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 250, 240, 21);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 34, 45));
        jLabel5.setText("Number of Seats Available");
        jLabel5.setMaximumSize(new java.awt.Dimension(223, 21));
        jLabel5.setMinimumSize(new java.awt.Dimension(223, 21));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 21));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(459, 220, 240, 21);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 34, 45));
        jLabel6.setText("Arrival Time (GMT)");
        jLabel6.setPreferredSize(new java.awt.Dimension(500, 21));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(459, 400, 240, 21);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 34, 45));
        jLabel7.setText("Departure Time (GMT)");
        jLabel7.setMaximumSize(new java.awt.Dimension(423, 21));
        jLabel7.setMinimumSize(new java.awt.Dimension(423, 21));
        jLabel7.setPreferredSize(new java.awt.Dimension(400, 21));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(459, 300, 240, 21);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 34, 45));
        jLabel8.setText("Cost of Ticket ($)");
        jLabel8.setPreferredSize(new java.awt.Dimension(600, 21));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(459, 480, 240, 21);

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(745, 480, 245, 29);

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(745, 400, 245, 29);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(745, 220, 245, 29);

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(745, 300, 245, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Route", " " }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(100, 170, 267, 29);

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setLabel("Back to Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 460, 160, 32);

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setLabel("Submit");
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 460, 100, 32);

        jDateChooser1.setDateFormatString("mm/dd/yyyy");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(100, 290, 267, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/resources/air_4.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-130, -20, 1270, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Welcome welcome = Welcome.getInstance() ;
        welcome.main() ;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Availability.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
